version: "2.2"

services:
  bot:
    build: src/
    restart: always
    depends_on:
      - utopia-api
    networks:
      - unetwork
    volumes:
      - ./../data/:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  db:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: uservice
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  utopia-api:
    image: uto9234/utopia-api
    restart: always
    ports:
      - 22825:22825
      - 25000:25000
    environment:
      XDG_RUNTIME_DIR: /tmp/runtime-root
    networks:
      - unetwork
    volumes:
      - ./data/account.db:/app/account.db
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

networks:
  unetwork:
