version: "2.2"

services:
  bot:
    build: src/
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: uservice
      DB_USER: user
      DB_PASS: password
      UTOPIA_TOKEN: FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      UTOPIA_HOST: utopia-api
      UTOPIA_PORT: 22825
    depends_on:
      - utopia-api
    networks:
      - unetwork
    volumes:
      - ./data/:/var/uservice/data

  db:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: uservice
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"

  utopia-api:
    image: uto9234/utopia-api
    ports:
      - 22825:22825
    environment:
      XDG_RUNTIME_DIR: /tmp/runtime-root
    networks:
      - unetwork
    volumes:
      - ./data/account.db:/app/account.db

networks:
  unetwork:
